# bundle exec jekyll serve
# C:\Users\tai\Documents\GitHub\atlesg.github.io
# https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/testing-your-github-pages-site-locally-with-jekyll

title: "Tai Le"
author: "Tai Le"
description: "My github website"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # use a dark header
dark_mode: false           # set to true to enable dark mode


# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  # - {file: "about-me.md", title: "About me"}
  - {file: "cv.md", title: "CV"}
  - {file: "projects.md", title: "Projects"}
  - {file: "blog.md", title: "Blog"}
  - {file: "hobbies.md", title: "Hobbies"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:"}
  - {title: Github, icon: github, url: "https://github.com/atlesg"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
